openapi: 3.0.3
info:
  version: v1
  title: OpenSearch Dashboards Saved Objects API
  contact:
    name: OpenSearch Dashboards Team
  description: |-
    OpenAPI schema for OpenSearch Dashboards Saved Objects API
tags:
  - name: saved objects
    description: Manage Dashboards saved objects, including dashboards, visualizations, saved search, and more.
paths:
  /api/saved_objects/{type}/{id}:
    get:
      tags:
        - saved objects
      summary: Retrieve a single saved object by type and id.
      parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/type'
      responses:
        '200':
          description: The saved object is successfully retrieved. 
          content:
            application/json:
              schema:
                type: object
        '404':
          description: The saved object does not exist.
          content:
            application/json:
              schema:
                type: object
    post:
      tags:
        - saved objects
      summary: Create a new saved object with type and id.
      parameters:
        - $ref: '#components/parameters/type'
        - $ref: '#components/parameters/id'
        - in: query
          name: overwrite
          description: If set to true, will overwrite the existing saved object with same type and id.
          schema: 
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - attributes
              properties:
                attributes:
                  type: object
                  description: The metadata of the saved object to be created, and the object is not validated.
                migrationVersion:
                  type: object
                  description: The information about the migrations that have been applied to this saved object to be created.
                references:
                  description: List of objects that describe other saved objects the created object references. 
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      type:
                        type: string
                initialNamespaces:
                  description: Namespaces that this saved object exists in. This attribute is only used for multi-namespace saved object types.
                  type: array
                  items:
                    type: string
                workspaces:
                  type: array
                  items:
                    type: string
                  description: Workspaces that this saved object exists in.
            examples:
              indexPattern:
                summary: Example of creating an index pattern saved object
                value:
                  attributes:
                    title: 'my-index-pattern'
                    fields: '[{"count":"1","name":"@timestamp","searchable":"true"}]'
                  references:
                    - id: '51339560-1d7c-11ef-b757-55fac6c80d9a'
                      name: 'dataSource'
                      type: 'data-source'
              vegaVisualization:
                summary: Example of creating a Vega visualization saved object
                value:
                  attributes:
                    title: 'my-vega-visualization'
                    visState: '{"title":"vegaVisualization","type":"vega","aggs":[]}}'
                    uiStateJSON: '{}'
                    description: ''
                    version: 1
                    kibanaSavedObjectMeta: {
                      searchSourceJSON: '{"query":{"language":"kuery","query":""},"filter":[]}'
                    }
                  references:
                    - id: '51339560-1d7c-11ef-b757-55fac6c80d9a'
                      name: 'dataSource'
                      type: 'data-source'
              dashboards:
                summary: Example of creating a dashboard saved object
                value:
                  attributes:
                    title: 'Revenue Dashboard'
                    description: 'Revenue dashboard'
                    panelsJSON: '[{"version":"2.9.0","gridData":{"x":0,"y":0,"w":24,"h":15,"i":"5db1d75d-f680-4869-a0e8-0f2b8b05b99c"},"panelIndex":"5db1d75d-f680-4869-a0e8-0f2b8b05b99c","embeddableConfig":{},"panelRefName":"panel_0"}]'
                    optionsJSON: '{"hidePanelTitles":false,"useMargins":true}'
                    version: 1
                    timeRestore: true
                    kibanaSavedObjectMeta: {
                      searchSourceJSON: '{"query":{"language":"kuery","query":""},"filter":[]}'
                    }
                  references:
                    - id: '37cc8650-b882-11e8-a6d9-e546fe2bba5f'
                      name: 'panel_0'
                      type: 'visualization'  
      responses:
        '200':
          description: The creation request is successful
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400_bad_request'
  /api/saved_objects/_find:
    get:
      tags:
        - saved objects
      summary: Find saved objects through query.
      parameters:
        - in: query
          name: type
          description: The type of saved objects to find.
          required: true
          schema:
            oneOf:
              - type: string
              - type: array
          example: dashboard
        - in: query
          name: per_page
          description: The number of saved objects to return per page.
          schema:
            type: integer
            minimum: 0
            default: 20
          example: 50
        - in: query
          name: page
          description: The page of objects to return.
          schema:
            type: integer 
            minimum: 0
            default: 1
          example: 1
        - in: query
          name: search
          description: The search query that filters the saved objects.
          schema:
            type: string
          example: "open*"
        - in: query
          name: default_search_operator
          description: The default operator for the search query.
          schema:
            type: string
            enum:
              - AND
              - OR
            default: OR
          example: OR
        - in: query
          name: search_fields
          description: The fields to search on by the query.
          schema:
            oneOf:
              - type: string
              - type: array
          example: title
        - in: query
          name: sort_field
          description: Sorts the response by selected field.
          schema:
            type: string
          example: _score
        - in: query
          name: has_reference
          description: Filters the saved objects that have a reference with the type and ID combination.
          schema:
            type: object
            properties:
              type:
                type: string
              id:
                type: string
          example: { "type": "visualization", "id": "37cc8650-b882-11e8-a6d9-e546fe2bba5f" }
        - in: query
          name: fields
          description: The fields to return in the response.
          schema:
            oneOf:
              - type: string
              - type: array
          example: title
        - in: query
          name: filter
          description: A filter string that you can filter the saved object with attributes.
          schema:
            type: string
          example: 'visualization.attributes.title:*'
        - in: query
          name: namespace
          description: Namespaces that this saved object exists in. This attribute is only used for multi-namespace saved object types.
          schema:
            oneOf:
              - type: string
              - type: array
        - in: query
          name: workspace
          description: Workspaces that this saved object exists in.
          schema:
            oneOf:
              - type: string
              - type: array
      responses:
        '200':
          description: The saved objects are successfully found.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400_bad_request'
components:
  parameters:
    type:
      name: type
      in: path
      description: The type of SavedObject to retrieve.
      required: true
      schema:
        type: string
    id: 
      name: id
      in: path
      description: Unique id of the saved object.
      required: true
      schema:
        type: string
  schemas:
    400_bad_request:
      title: Bad request
      type: object
      required:
        - error
        - message
        - statusCode
      properties:
        error:
          type: string
          enum:
            - Bad Request
        message:
          type: string
        statusCode:
          type: integer
          enum:
            - 400