[role="xpack"]
[[monitoring-opensearch-dashboards]]
= Collect monitoring data using legacy collectors
++++
<titleabbrev>Legacy collection methods</titleabbrev>
++++

If you enable the Elastic {monitor-features} in your cluster, you can
optionally collect metrics about {osd}.

[IMPORTANT]
=========================
{metricbeat} is the recommended method for collecting and shipping monitoring
data to a monitoring cluster.

If you have previously configured legacy collection methods, you should migrate
to using {metricbeat} collection methods. Use either {metricbeat} collection or
legacy collection methods; do not use both.

For the recommended method, refer to <<monitoring-metricbeat>>.
=========================

The following method involves sending the metrics to the production cluster,
which ultimately routes them to the monitoring cluster.

To learn about monitoring in general, see
{ref}/monitor-opensearch-cluster.html[Monitor a cluster].

. Set the `xpack.monitoring.collection.enabled` setting to `true` on each
node in the production cluster. By default, it is is disabled (`false`).
+
--
NOTE: You can specify this setting in either the `opensearch.yml` on each
node or across the cluster as a dynamic cluster setting. If
{stack-security-features} are enabled, you must have `monitor` cluster
privileges to view the cluster settings and `manage` cluster privileges to
change them.

--

** To update the cluster settings in {osd}:

... Open {osd} in your web browser.
+
--
By default, if you are running {osd} locally, go to `http://localhost:5601/`.

If {security-features} are enabled, log in.
--

... Open the main menu, then click *Stack Monitoring*. If data collection is
disabled, you are prompted to turn it on. 

** From the Console or command line, set `xpack.monitoring.collection.enabled`
to `true` on the production cluster. +
+
--
For example, you can use the following APIs to review and change this setting:

[source,js]
----------------------------------
GET _cluster/settings

PUT _cluster/settings
{
  "persistent": {
    "xpack.monitoring.collection.enabled": true
  }
}
----------------------------------

For more information, see {ref}/monitoring-settings.html[Monitoring settings in {opensearch}]
and {ref}/cluster-update-settings.html[Cluster update settings].
--

. Verify that `monitoring.enabled` and
`monitoring.opensearchDashboards.collection.enabled` are set to `true` in the
`opensearch_dashboards.yml` file. These are the default values. For
more information, see <<monitoring-settings-osd,Monitoring settings in {osd}>>.

. Identify where to send monitoring data. {osd} automatically
sends metrics to the {opensearch} cluster specified in the `opensearch.hosts` setting
in the `opensearch_dashboards.yml` file. This property has a default value of
`http://localhost:9200`. +
+
--
[TIP]
===============================
In production environments, we strongly recommend using a separate cluster
(referred to as the _monitoring cluster_) to store the data. Using a separate
monitoring cluster prevents production cluster outages from impacting your
ability to access your monitoring data. It also prevents monitoring activities
from impacting the performance of your production cluster.

If {security-features} are enabled on the production cluster, use an HTTPS
URL such as `https://<your_production_cluster>:9200` in this setting.
===============================

--

. If {security-features} are enabled on the production cluster:

.. Verify that there is a
valid user ID and password in the `opensearch.username` and
`opensearch.password` settings in the `opensearch_dashboards.yml` file. These values are
used when {osd} sends monitoring data to the production cluster.

.. <<configuring-tls-osd-opensearch,Configure encryption for traffic between {osd} and {opensearch}>>.

. <<start-stop,Start {osd}>>.

. <<monitoring-data,View the monitoring data in {osd}>>.
