[role="xpack"]
[[monitor-troubleshooting]]
= Troubleshooting monitoring in {osd}
++++
<titleabbrev>Troubleshooting</titleabbrev>
++++

Use the information in this section to troubleshoot common problems and find 
answers for frequently asked questions related to the {osd} {monitor-features}.

[float]
== Cannot view the cluster because the license information is invalid

*Symptoms:*

The following error appears in a banner at the top of the screen in {osd} on the 
*Stack Monitoring > Clusters* page:
`You can't view the "<my_cluster>" cluster because the license information is invalid.`

*Resolution:*

You cannot monitor a version 6.3 or later cluster from {osd} version 6.2 or earlier. 
To resolve this issue, upgrade {osd} to 6.3 or later. See 
{stack-ref}/upgrading-elastic-stack.html[Upgrading the {stack}]. 

[float]
== No monitoring data is visible in {osd}

*Symptoms:*

The *Stack Monitoring* page in {osd} is empty. 

*Resolution:*

. Confirm that you are not using {osd} 6.7.0 or 6.7.1. If you have a version 7.0
monitoring cluster, a version 6.7 production cluster and {osd} version 6.7.0 or
6.7.1, you cannot see the monitoring data in {osd}. For more information, see
https://github.com/elastic/opensearch-dashboards/issues/34357

. Confirm that {osd} is seeking monitoring data from the appropriate {opensearch} URL.
By default, data is retrieved from the cluster specified in the 
`opensearch.hosts` setting in the `opensearch_dashboards.yml` file. If you want to retrieve it
from a different monitoring cluster, set `monitoring.ui.opensearch.hosts`.
See <<monitoring-settings-osd>>.

. Confirm that there is monitoring data available at that URL. It is stored in
indices such as `.monitoring-opensearch-dashboards-*` and `.monitoring-opensearch-*`. At a minimum, you
must have monitoring data for the {opensearch} production cluster. Once that data exists,
{osd} can display monitoring data for other products in the cluster.

. Set the time filter to “Last 1 hour”.  When monitoring data appears in your
cluster, the page automatically refreshes with the monitoring summary.

