[[setup]]
= Set up

[partintro]
--
This section includes information on how to setup OpenSearchDashboards and get it running,
including:

* Downloading
* Installing
* Starting
* Configuring
* Upgrading

[[supported-platforms]]
[float]
== Supported platforms

Packages of OpenSearchDashboards are provided for and tested against Linux, Darwin, and
Windows. Since OpenSearchDashboards runs on Node.js, we include the necessary Node.js
binaries for these platforms. Running OpenSearchDashboards against a separately maintained
version of Node.js is not supported.

[float]
[[opensearch-version]]
== OpenSearch version

OpenSearchDashboards should be configured to run against an OpenSearch node of the same
version. This is the officially supported configuration.

Running different major version releases of OpenSearchDashboards and OpenSearch (e.g.
OpenSearchDashboards 5.x and OpenSearch 2.x) is not supported, nor is running a minor
version of OpenSearchDashboards that is newer than the version of OpenSearch (e.g. OpenSearchDashboards
5.1 and OpenSearch 5.0).

Running a minor version of OpenSearch that is higher than OpenSearchDashboards will
generally work in order to facilitate an upgrade process where OpenSearch
is upgraded first (e.g. OpenSearchDashboards 5.0 and OpenSearch 5.1). In this
configuration, a warning will be logged on OpenSearchDashboards server startup, so it's only
meant to be temporary until OpenSearchDashboards is upgraded to the same version as
OpenSearch.

Running different patch version releases of OpenSearchDashboards and OpenSearch (e.g.
OpenSearchDashboards 5.0.0 and OpenSearch 5.0.1) is generally supported, though we
encourage users to run the same versions of OpenSearchDashboards and OpenSearch down to
the patch version.
--

include::{osd-repo-dir}/setup/install.asciidoc[]

include::{osd-repo-dir}/setup/settings.asciidoc[]

include::{osd-repo-dir}/setup/start-stop.asciidoc[]

include::{osd-repo-dir}/setup/access.asciidoc[]

include::{osd-repo-dir}/setup/connect-to-opensearch.asciidoc[]

include::{osd-repo-dir}/setup/production.asciidoc[]

include::{osd-repo-dir}/setup/upgrade.asciidoc[]
