[[install]]
== Install {osd}

[float]
=== Hosted {osd}

If you are running our hosted OpenSearch Service on Elastic Cloud, you access OpenSearchDashboards with a single click. (You can {opensearchs-trial}[sign up for a free trial] and start exploring data in minutes.)

[float]
=== Install {osd} yourself

NOTE: Starting with version 6.0.0, OpenSearchDashboards only supports 64 bit operating systems.

OpenSearchDashboards is provided in the following package formats:

[horizontal]
`tar.gz`/`zip`::

The `tar.gz` packages are provided for installation on Linux and Darwin and are
the easiest choice for getting started with OpenSearchDashboards.
+
The `zip` package is the only supported package for Windows.
+
<<targz>> or <<windows>>

`deb`::

The `deb` package is suitable for Debian, Ubuntu, and other Debian-based
systems.  Debian packages may be downloaded from the Elastic website or from
our Debian repository.
+
<<deb>>

`rpm`::

The `rpm` package is suitable for installation on Red Hat, Centos, SLES,
OpenSuSE and other RPM-based systems.  RPMs may be downloaded from the
Elastic website or from our RPM repository.
+
<<rpm>>

`docker`::

Images are available for running OpenSearchDashboards as a Docker container. They may be
downloaded from the Elastic Docker Registry.
+
<<docker,Running OpenSearchDashboards on Docker>>

`brew`::

Formulae are available from the Elastic Homebrew tap for installing {osd} on macOS with the Homebrew package manager.
+
<<brew>>

IMPORTANT: If your OpenSearch installation is protected by
{ref}/opensearch-security.html[{stack-security-features}] see
{opensearch-dashboards-ref}/using-opensearch-dashboards-with-security.html[Configuring security in {osd}] for
additional setup instructions.

include::install/targz.asciidoc[]

include::install/windows.asciidoc[]

include::install/deb.asciidoc[]

include::install/rpm.asciidoc[]

include::{osd-repo-dir}/setup/docker.asciidoc[]

include::install/brew.asciidoc[]
