[[secure-settings]]
=== Secure settings

Some settings are sensitive, and relying on filesystem permissions to protect
their values is not sufficient. For this use case, OpenSearchDashboards provides a
keystore, and the `opensearch-dashboards-keystore` tool to manage the settings in the keystore.

NOTE: All commands here should be run as the user which will run OpenSearchDashboards.

[float]
[[creating-keystore]]
=== Create the keystore

To create the `opensearchDashboards.keystore`, use the `create` command:

[source,sh]
----------------------------------------------------------------
bin/opensearch-dashboards-keystore create
----------------------------------------------------------------

The file `opensearchDashboards.keystore` will be created in the directory defined by the
<<path-data, `path.data`>> configuration setting.

[float]
[[list-settings]]
=== List settings in the keystore

A list of the settings in the keystore is available with the `list` command:

[source,sh]
----------------------------------------------------------------
bin/opensearch-dashboards-keystore list
----------------------------------------------------------------

[float]
[[add-string-to-keystore]]
=== Add string settings

Sensitive string settings, like authentication credentials for OpenSearch
can be added using the `add` command:

[source,sh]
----------------------------------------------------------------
bin/opensearch-dashboards-keystore add the.setting.name.to.set
----------------------------------------------------------------

Once added to the keystore, these setting will be automatically applied
to this instance of OpenSearchDashboards when started. For example if you do

[source,sh]
----------------------------------------------------------------
bin/opensearch-dashboards-keystore add opensearch.username
----------------------------------------------------------------

you will be prompted to provide the value for opensearch.username.
(Your input will show as asterisks.)

The tool will prompt for the value of the setting. To pass the value
through stdin, use the `--stdin` flag:

[source,sh]
----------------------------------------------------------------
cat /file/containing/setting/value | bin/opensearch-dashboards-keystore add the.setting.name.to.set --stdin
----------------------------------------------------------------

[float]
[[remove-settings]]
=== Remove settings

To remove a setting from the keystore, use the `remove` command:

[source,sh]
----------------------------------------------------------------
bin/opensearch-dashboards-keystore remove the.setting.name.to.remove
----------------------------------------------------------------
