/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import moment from 'moment';
import { ChatExportData, ChatExportOptions } from './types';

export function generateMarkdownReport(data: ChatExportData, options: ChatExportOptions): string {
  const timestamp = data.metadata?.timestamp || new Date().toISOString();
  const formattedDate = moment(timestamp).format('MMMM D, YYYY h:mm A z');

  const sections: string[] = [];

  sections.push(`# Investigation Report — ${data.question}`);
  sections.push('');
  sections.push(`**Date:** ${formattedDate}`);
  if (data.metadata?.threadId) {
    sections.push(`**Thread ID:** ${data.metadata.threadId}`);
  }
  sections.push('');

  if (data.note) {
    sections.push(`> **Note from investigator:** ${data.note}`);
    sections.push('');
  }

  sections.push('## Investigation Question');
  sections.push('');
  sections.push(data.question);
  sections.push('');

  if (options.includeAISummary) {
    sections.push('## AI Analysis');
    sections.push('');
    sections.push(data.answer);
    sections.push('');
  }

  if (options.includeVisualizations && data.visualizations.length > 0) {
    sections.push('## Visualizations');
    sections.push('');
    sections.push(
      `*${data.visualizations.length} visualization(s) were captured. Visualizations are only available in the PDF export format.*`
    );
    sections.push('');
  }

  if (options.includeTraces && data.traces.length > 0) {
    sections.push('## Evidence (Agent Investigation Steps)');
    sections.push('');

    data.traces.forEach((trace, i) => {
      sections.push(`### Step ${i + 1} — ${trace.toolName}`);
      sections.push('');
      if (trace.arguments) {
        sections.push('**Input:**');
        sections.push('```');
        sections.push(trace.arguments);
        sections.push('```');
        sections.push('');
      }
      if (trace.result) {
        sections.push('**Output:**');
        sections.push('```');
        sections.push(trace.result);
        sections.push('```');
        sections.push('');
      }
      if (trace.error) {
        sections.push('**Error:**');
        sections.push('```');
        sections.push(trace.error);
        sections.push('```');
        sections.push('');
      }
    });
  }

  if (options.includeMetadata && data.metadata) {
    sections.push('## Metadata');
    sections.push('');
    sections.push('| Field | Value |');
    sections.push('|-------|-------|');
    sections.push(`| Timestamp | ${formattedDate} |`);
    if (data.metadata.threadId) {
      sections.push(`| Thread ID | ${data.metadata.threadId} |`);
    }
    sections.push('');
  }

  sections.push('---');
  sections.push(
    `*Generated by OpenSearch AI Investigation • ${formattedDate} • This report is a point-in-time snapshot and may not reflect current data.*`
  );

  return sections.join('\n');
}
