[[deb]]
=== Install {osd} with Debian package
++++
<titleabbrev>Install with Debian package</titleabbrev>
++++

The Debian package for OpenSearchDashboards can be <<install-deb,downloaded from our website>>
or from our <<deb-repo,APT repository>>. It can be used to install
OpenSearchDashboards on any Debian-based system such as Debian and Ubuntu.

This package is free to use under the Elastic license. It contains open source
and free commercial features and access to paid commercial features.
<<managing-licenses,Start a 30-day trial>> to try out all of the
paid commercial features. See the
https://www.elastic.co/subscriptions[Subscriptions] page for information about
Elastic license levels.

The latest stable version of OpenSearchDashboards can be found on the
link:/downloads/opensearch-dashboards[Download OpenSearchDashboards] page. Other versions can
be found on the link:/downloads/past-releases[Past Releases page].

[[deb-key]]
==== Import the Elastic PGP key

include::key.asciidoc[]

[source,sh]
-------------------------
wget -qO - https://artifacts.elastic.co/GPG-KEY-opensearch | sudo apt-key add -
-------------------------

[[deb-repo]]
==== Install from the APT repository

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

You may need to install the `apt-transport-https` package on Debian before proceeding:

[source,sh]
--------------------------------------------------
sudo apt-get install apt-transport-https
--------------------------------------------------

Save the repository definition to  +/etc/apt/sources.list.d/elastic-{major-version}.list+:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}-prerelease/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]


[WARNING]
==================================================

Do not use `add-apt-repository` as it will add a `deb-src` entry as well, but
we do not provide a source package. If you have added the `deb-src` entry, you
will see an error like the following:

    Unable to find expected entry 'main/source/Sources' in Release file
    (Wrong sources.list entry or malformed file)

Delete the `deb-src` entry from the `/etc/apt/sources.list` file and the
installation should work as expected.
==================================================

You can install the OpenSearchDashboards Debian package with:

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install opensearchDashboards
--------------------------------------------------

[WARNING]
==================================================
If two entries exist for the same OpenSearchDashboards repository, you will see an error like this during `apt-get update`:

["literal",subs="attributes,callouts"]

Duplicate sources.list entry https://artifacts.elastic.co/packages/{major-version}/apt/ ...`

Examine +/etc/apt/sources.list.d/opensearch-dashboards-{major-version}.list+ for the duplicate entry or locate the duplicate entry amongst the files in `/etc/apt/sources.list.d/` and the `/etc/apt/sources.list` file.
==================================================

endif::[]

ifeval::["{release-state}"!="unreleased"]

[NOTE]
==================================================

An alternative package, `opensearch-dashboards-oss`,  which contains only features that are available under the
Apache 2.0 license is also available. To install it, use the following sources list:

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/oss-{major-version}-prerelease/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"!="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/oss-{major-version}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]

==================================================

endif::[]

[[install-deb]]
==== Download and install the Debian package manually

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Debian package for OpenSearchDashboards v{version} can be downloaded from the website and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-amd64.deb
shasum -a 512 opensearch-dashboards-{version}-amd64.deb <1>
sudo dpkg -i opensearch-dashboards-{version}-amd64.deb
--------------------------------------------
<1> Compare the SHA produced by `shasum` with the
    https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-amd64.deb.sha512[published SHA].

Alternatively, you can download the following package, which contains only
features that are available under the Apache 2.0 license:
https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-oss-{version}-amd64.deb

endif::[]

==== SysV `init` vs `systemd`

include::init-systemd.asciidoc[]

[[deb-running-init]]
include::deb-init.asciidoc[]

[[deb-running-systemd]]

include::systemd.asciidoc[]

[[deb-configuring]]
==== Configure {osd} via the config file

OpenSearchDashboards loads its configuration from the `/etc/opensearch-dashboards/opensearch_dashboards.yml`
file by default.  The format of this config file is explained in
{opensearch-dashboards-ref}/settings.html[Configuring OpenSearchDashboards].

[[deb-layout]]
==== Directory layout of Debian package

The Debian package places config files, logs, and the data directory in the appropriate
locations for a Debian-based system:


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearchDashboards home directory or `$OPENSEARCH_DASHBOARDS_HOME`
  | /usr/share/opensearch-dashboards
 d|

| bin
  | Binary scripts including `opensearchDashboards` to start the OpenSearchDashboards server
    and `opensearch-dashboards-plugin` to install plugins
  | /usr/share/opensearch-dashboards/bin
 d|

| config
  | Configuration files including `opensearch_dashboards.yml`
  | /etc/opensearch-dashboards
 d|

| data
  | The location of the data files written to disk by OpenSearchDashboards and its plugins
  | /var/lib/opensearch-dashboards
  | path.data

| logs
    | Logs files location
    |  /var/log/opensearch-dashboards
    | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | /usr/share/opensearch-dashboards/plugins
 d|

|=======================================================================
