[[rpm]]
=== Install {osd} with RPM
++++
<titleabbrev>Install with RPM</titleabbrev>
++++


The RPM for OpenSearchDashboards can be <<install-rpm,downloaded from our website>>
or from our <<rpm-repo,RPM repository>>. It can be used to install
OpenSearchDashboards on any RPM-based system such as OpenSuSE, SLES, Centos, Red Hat,
and Oracle Enterprise.

NOTE: RPM install is not supported on distributions with old versions of RPM,
such as SLES 11 and CentOS 5.  Please see <<targz>> instead.

This package is free to use under the Elastic license. It contains open source
and free commercial features and access to paid commercial features.
<<managing-licenses,Start a 30-day trial>> to try out all of the
paid commercial features. See the
https://www.elastic.co/subscriptions[Subscriptions] page for information about
Elastic license levels.

The latest stable version of OpenSearchDashboards can be found on the
link:/downloads/opensearch-dashboards[Download OpenSearchDashboards] page. Other versions can
be found on the link:/downloads/past-releases[Past Releases page].

[[rpm-key]]
==== Import the Elastic PGP key

include::key.asciidoc[]

[source,sh]
-------------------------
rpm --import https://artifacts.elastic.co/GPG-KEY-opensearch
-------------------------

[[rpm-repo]]
==== Installing from the RPM repository

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

Create a file called `opensearchDashboards.repo` in the `/etc/yum.repos.d/` directory
for RedHat based distributions, or in the `/etc/zypp/repos.d/` directory for
OpenSuSE based distributions, containing:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[opensearch-dashboards-{major-version}]
name=OpenSearchDashboards repository for {major-version} packages
baseurl=https://artifacts.elastic.co/packages/{major-version}/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-opensearch
enabled=1
autorefresh=1
type=rpm-md
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[opensearch-dashboards-{major-version}]
name=OpenSearchDashboards repository for {major-version} packages
baseurl=https://artifacts.elastic.co/packages/{major-version}-prerelease/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-opensearch
enabled=1
autorefresh=1
type=rpm-md
--------------------------------------------------

endif::[]

And your repository is ready for use. You can now install OpenSearchDashboards with one of the following commands:

[source,sh]
--------------------------------------------------
sudo yum install opensearchDashboards <1>
sudo dnf install opensearchDashboards <2>
sudo zypper install opensearchDashboards <3>
--------------------------------------------------
<1> Use `yum` on CentOS and older Red Hat based distributions.
<2> Use `dnf` on Fedora and other newer Red Hat distributions.
<3> Use `zypper` on OpenSUSE based distributions

endif::[]

ifeval::["{release-state}"!="unreleased"]

[NOTE]
==================================================

An alternative package, `opensearch-dashboards-oss`, which contains only features that are available under the
Apache 2.0 license is also available. To install it, use the following `baseurl` in your `opensearchDashboards.repo` file:

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
baseurl=https://artifacts.elastic.co/packages/oss-{major-version}-prerelease/yum
--------------------------------------------------

endif::[]

ifeval::["{release-state}"!="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
baseurl=https://artifacts.elastic.co/packages/oss-{major-version}/yum
--------------------------------------------------

endif::[]

==================================================

endif::[]

[[install-rpm]]
==== Download and install the RPM manually

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The RPM for OpenSearchDashboards v{version} can be downloaded from the website and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-x86_64.rpm
shasum -a 512 opensearch-dashboards-{version}-x86_64.rpm <1>
sudo rpm --install opensearch-dashboards-{version}-x86_64.rpm
--------------------------------------------
<1> Compare the SHA produced by `shasum` with the
    https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-x86_64.rpm.sha512[published SHA].

Alternatively, you can download the following package, which contains only
features that are available under the Apache 2.0 license:
https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-oss-{version}-x86_64.rpm

endif::[]

==== SysV `init` vs `systemd`

include::init-systemd.asciidoc[]

[[rpm-running-init]]
include::rpm-init.asciidoc[]

[[rpm-running-systemd]]
include::systemd.asciidoc[]

[[rpm-configuring]]
==== Configure {osd} via the config file

OpenSearchDashboards loads its configuration from the `/etc/opensearch-dashboards/opensearch_dashboards.yml`
file by default.  The format of this config file is explained in
{opensearch-dashboards-ref}/settings.html[Configuring OpenSearchDashboards].

[[rpm-layout]]
==== Directory layout of RPM

The RPM places config files, logs, and the data directory in the appropriate
locations for an RPM-based system:


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearchDashboards home directory or `$OPENSEARCH_DASHBOARDS_HOME`
  | /usr/share/opensearch-dashboards
 d|

| bin
  | Binary scripts including `opensearchDashboards` to start the OpenSearchDashboards server
    and `opensearch-dashboards-plugin` to install plugins
  | /usr/share/opensearch-dashboards/bin
 d|

| config
  | Configuration files including `opensearch_dashboards.yml`
  | /etc/opensearch-dashboards
 d|

| data
  | The location of the data files written to disk by OpenSearchDashboards and its plugins
  | /var/lib/opensearch-dashboards
  | path.data

| logs
    | Logs files location
    |  /var/log/opensearch-dashboards
    | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | /usr/share/opensearch-dashboards/plugins
 d|

|=======================================================================
