[[targz]]
=== Install {osd} from archive on Linux or macOS
++++
<titleabbrev>Install from archive on Linux or macOS</titleabbrev>
++++

OpenSearchDashboards is provided for Linux and Darwin as a `.tar.gz` package. These packages
are the easiest formats to use when trying out OpenSearchDashboards.

These packages are free to use under the Elastic license. They contain open
source and free commercial features and access to paid commercial features.
<<managing-licenses,Start a 30-day trial>> to try out all of the
paid commercial features. See the
https://www.elastic.co/subscriptions[Subscriptions] page for information about
Elastic license levels.

The latest stable version of OpenSearchDashboards can be found on the
link:/downloads/opensearch-dashboards[Download OpenSearchDashboards] page.
Other versions can be found on the
link:/downloads/past-releases[Past Releases page].


[[install-linux64]]
==== Download and install the Linux 64-bit package

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Linux archive for OpenSearchDashboards v{version} can be downloaded and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
curl -O https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-linux-x86_64.tar.gz
curl https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-linux-x86_64.tar.gz.sha512 | shasum -a 512 -c - <1>
tar -xzf opensearch-dashboards-{version}-linux-x86_64.tar.gz
cd opensearch-dashboards-{version}-linux-x86_64/ <2>
--------------------------------------------
<1> Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
    `opensearch-dashboards-{version}-linux-x86_64.tar.gz: OK`.
<2> This directory is known as `$OPENSEARCH_DASHBOARDS_HOME`.

endif::[]


[[install-darwin64]]
==== Download and install the Darwin package

[IMPORTANT]
.macOS Gatekeeper warnings
====
Apple's rollout of stricter notarization requirements affected the notarization
of the {version} {osd} artifacts. If macOS Catalina displays a dialog when you
first run {osd} that interrupts it, you will need to take an action to allow it
to run.

To prevent Gatekeeper checks on the {osd} files, run the following command on the
downloaded `.tar.gz` archive or the directory to which was extracted:
[source,sh]
----
xattr -d -r com.apple.quarantine <archive-or-directory>
----

Alternatively, you can add a security override if a Gatekeeper popup appears by
following the instructions in the _How to open an app that hasn’t been notarized
or is from an unidentified developer_ section of
https://support.apple.com/en-us/HT202491[Safely open apps on your Mac].
====

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Darwin archive for OpenSearchDashboards v{version} can be downloaded and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
curl -O https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-darwin-x86_64.tar.gz
curl https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-darwin-x86_64.tar.gz.sha512 | shasum -a 512 -c - <1>
tar -xzf opensearch-dashboards-{version}-darwin-x86_64.tar.gz
cd opensearch-dashboards-{version}-darwin-x86_64/ <2>
--------------------------------------------
<1> Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
    `opensearch-dashboards-{version}-darwin-x86_64.tar.gz: OK`.
<2> This directory is known as `$OPENSEARCH_DASHBOARDS_HOME`.

Alternatively, you can download the following package, which contains only
features that are available under the Apache 2.0 license:
https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-oss-{version}-darwin-x86_64.tar.gz

endif::[]


[[targz-running]]
include::targz-running.asciidoc[]


[[targz-configuring]]
==== Configure {osd} via the config file

OpenSearchDashboards loads its configuration from the `$OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml`
file by default.  The format of this config file is explained in
{opensearch-dashboards-ref}/settings.html[Configuring OpenSearchDashboards].


[[targz-layout]]
==== Directory layout of `.tar.gz` archives

The `.tar.gz` packages are entirely self-contained. All files and directories
are, by default, contained within `$OPENSEARCH_DASHBOARDS_HOME` -- the directory created when
unpacking the archive.

This is very convenient because you don't have to create any directories to
start using OpenSearchDashboards, and uninstalling OpenSearchDashboards is as easy as removing the
`$OPENSEARCH_DASHBOARDS_HOME` directory.  However, it is advisable to change the default
locations of the config and data directories so that you do not delete
important data later on.


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearchDashboards home directory or `$OPENSEARCH_DASHBOARDS_HOME`
 d| Directory created by unpacking the archive
 d|

| bin
  | Binary scripts including `opensearchDashboards` to start the OpenSearchDashboards server
    and `opensearch-dashboards-plugin` to install plugins
  | $OPENSEARCH_DASHBOARDS_HOME\bin
 d|

| config
  | Configuration files including `opensearch_dashboards.yml`
  | $OPENSEARCH_DASHBOARDS_HOME\config
 d|

| data
  | The location of the data files written to disk by OpenSearchDashboards and its plugins
  | $OPENSEARCH_DASHBOARDS_HOME\data
 d|

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | $OPENSEARCH_DASHBOARDS_HOME\plugins
 d|

|=======================================================================
