[[windows]]
=== Install {osd} on Windows
++++
<titleabbrev>Install on Windows</titleabbrev>
++++

OpenSearchDashboards can be installed on Windows using the `.zip` package.

This package is free to use under the Elastic license. It contains open source
and free commercial features and access to paid commercial features.
<<managing-licenses,Start a 30-day trial>> to try out all of the
paid commercial features. See the
https://www.elastic.co/subscriptions[Subscriptions] page for information about
Elastic license levels.

The latest stable version of OpenSearchDashboards can be found on the
link:/downloads/opensearch-dashboards[Download OpenSearchDashboards] page.
Other versions can be found on the
link:/downloads/past-releases[Past Releases page].

[[install-windows]]
==== Download and install the `.zip` package

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearchDashboards has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

Download the `.zip` windows archive for OpenSearchDashboards v{version} from
https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-{version}-windows-x86_64.zip

Unzip it with your favourite unzip tool. This will create a folder called
opensearch-dashboards-{version}-windows-x86_64, which we will refer to as `$OPENSEARCH_DASHBOARDS_HOME`. In a
terminal window, `CD` to the `$OPENSEARCH_DASHBOARDS_HOME` directory, for instance:


["source","sh",subs="attributes"]
----------------------------
CD c:\opensearch-dashboards-{version}-windows-x86_64
----------------------------

Alternatively, you can download the following package, which contains only
features that are available under the Apache 2.0 license:
https://artifacts.elastic.co/downloads/opensearch-dashboards/opensearch-dashboards-oss-{version}-windows-x86_64.zip

endif::[]

[[windows-running]]
include::windows-running.asciidoc[]

[[windows-configuring]]
==== Configure {osd} via the config file

OpenSearchDashboards loads its configuration from the `$OPENSEARCH_DASHBOARDS_HOME/config/opensearch_dashboards.yml`
file by default.  The format of this config file is explained in
{opensearch-dashboards-ref}/settings.html[Configuring OpenSearchDashboards].

[[windows-layout]]
==== Directory layout of `.zip` archive

The `.zip` package is entirely self-contained. All files and directories are,
by default, contained within `$OPENSEARCH_DASHBOARDS_HOME` -- the directory created when
unpacking the archive.

This is very convenient because you don't have to create any directories to
start using OpenSearchDashboards, and uninstalling OpenSearchDashboards is as easy as removing the
`$OPENSEARCH_DASHBOARDS_HOME` directory.  However, it is advisable to change the default
locations of the config and data directories so that you do not delete
important data later on.


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearchDashboards home directory or `$OPENSEARCH_DASHBOARDS_HOME`
 d| Directory created by unpacking the archive
 d|

| bin
  | Binary scripts including `opensearchDashboards` to start the OpenSearchDashboards server
    and `opensearch-dashboards-plugin` to install plugins
  | $OPENSEARCH_DASHBOARDS_HOME\bin
 d|

| config
  | Configuration files including `opensearch_dashboards.yml`
  | $OPENSEARCH_DASHBOARDS_HOME\config
 d|

| data
  | The location of the data files written to disk by OpenSearchDashboards and its plugins
  | $OPENSEARCH_DASHBOARDS_HOME\data
 d|

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | $OPENSEARCH_DASHBOARDS_HOME\plugins
 d|

|=======================================================================
