#!/bin/sh
# postinst script for wazuh-dashboard
# Copyright (C) 2021, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

set -e

export NAME=wazuh-dashboard
export CONFIG_DIR=/etc/"${NAME}"
export INSTALLATION_DIR=/usr/share/"${NAME}"

#
# This script is executed in the pre-remove phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=upgrade   : indicates an upgrade

# source the default env file
if [ -f "/etc/default/${NAME}" ]; then
    . "/etc/default/${NAME}"
fi

STOP_REQUIRED=false
REMOVE_SERVICE=false

case "$1" in

# Debian ####################################################
remove)
    STOP_REQUIRED=true
    REMOVE_SERVICE=true
    ;;
upgrade | deconfigure | failed-upgrade) ;;

*)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;

esac

# Stops the service
if [ "$STOP_REQUIRED" = "true" ]; then
    echo -n "Stopping wazuh-dashboard service..."
    if command -v systemctl >/dev/null; then
        systemctl --no-reload stop "${NAME}".service

    elif [ -x /etc/init.d/"${NAME}" ]; then
        if command -v invoke-rc.d >/dev/null; then
            invoke-rc.d "${NAME}" stop
        else
            /etc/init.d/"${NAME}" stop
        fi

    # older suse linux distributions do not ship with systemd
    # but do not have an /etc/init.d/ directory
    # this tries to start the wazuh-dashboard service on these
    # as well without failing this script
    elif [ -x /etc/rc.d/init.d/"${NAME}" ]; then
        /etc/rc.d/init.d/"${NAME}" stop
    fi
    echo " OK"
fi

if [ "$REMOVE_SERVICE" = "true" ]; then
    if command -v systemctl >/dev/null; then
        systemctl disable "${NAME}".service >/dev/null 2>&1 || true
    fi

    if command -v chkconfig >/dev/null; then
        chkconfig --del "${NAME}" 2>/dev/null || true
    fi

    if command -v update-rc.d >/dev/null; then
        update-rc.d "${NAME}" remove >/dev/null || true
    fi
fi
