[role="xpack"]
[[configuring-reporting]]
== Reporting configuration

You can configure settings in `opensearch_dashboards.yml` to control how the {report-features}
communicate with the {osd} server, manages background jobs, and captures
screenshots. See <<reporting-settings-osd, Reporting Settings>> for the complete
list of settings.

[float]
[[encryption-keys]]
=== Encryption keys for multiple {osd} instances

By default, a new encryption key is generated for the {report-features} each
time you start {osd}. This means if a static encryption key is not persisted in
the {osd} configuration, any pending reports will fail when you restart {osd}.

If you are load balancing across multiple {osd} instances, they need to have
the same reporting encryption key. Otherwise, report generation will fail if a
report is queued through one instance and another instance picks up the job
from the report queue. The other instance will not be able to decrypt the
reporting job metadata.

To set a static encryption key for reporting, set the
`xpack.reporting.encryptionKey` property in the `opensearch_dashboards.yml`
configuration file. You can use any alphanumeric, at least 32 characters long text string as the encryption key.

[source,yaml]
--------------------------------------------------------------------------------
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

[float]
[[report-indices]]
=== Report indices for multiple {osd} workspaces

If you divide workspaces in an Elastic cluster using multiple {osd} instances
with a different `opensearch-dashboards.index` setting per instance, you must set a unique `xpack.reporting.index`
setting per `opensearch-dashboards.index`. Otherwise, report generation will periodically fail
if a report is queued through an instance with one `opensearch-dashboards.index` setting, and
an instance with a different `opensearch-dashboards.index` attempts to claim the job.

OpenSearchDashboards instance A:
[source,yaml]
--------------------------------------------------------------------------------
opensearch-dashboards.index: ".opensearch-dashboards-a"
xpack.reporting.index: ".reporting-a"
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

OpenSearchDashboards instance B:
[source,yaml]
--------------------------------------------------------------------------------
opensearch-dashboards.index: ".opensearch-dashboards-b"
xpack.reporting.index: ".reporting-b"
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

NOTE: If security is enabled, the `xpack.reporting.index` setting should begin
with `.reporting-` in order for the `opensearch_dashboards_system` role to have the necessary
privileges over the index.

[float]
[[using-reverse-proxies]]
=== Use reverse proxies

If your {osd} instance requires a reverse proxy (NGINX, Apache, etc.) for
access, because of rewrite rules or special headers being added by the proxy,
then you need to configure the `xpack.reporting.opensearchDashboardsServer` settings to make
the headless browser process connect to the proxy in <<reporting-opensearch-dashboards-server-settings, OpenSearchDashboards server settings>>.

NOTE: A headless browser runs on the OpenSearchDashboards server to open a OpenSearchDashboards page for
capturing screenshots. Configuring the `xpack.reporting.opensearchDashboardsServer` settings
to point to a proxy host requires that the OpenSearchDashboards server has network access to
the proxy.

include::{osd-repo-dir}/user/security/reporting.asciidoc[]
include::network-policy.asciidoc[]
