[[external-plugin-functional-tests]]
== Functional Tests for Plugins outside the {osd} repo

Plugins use the `FunctionalTestRunner` by running it out of the {osd} repo. Ensure that your {osd} Development Environment is setup properly before continuing.

[discrete]
=== Writing your own configuration

Every project or plugin should have its own `FunctionalTestRunner` config file. Just like {osd}'s, this config file will define all of the test files to load, providers for Services and PageObjects, as well as configuration options for certain services.

To get started copy and paste this example to `test/functional/config.js`:

["source","js"]
-----------
import { resolve } from 'path';
import { REPO_ROOT } from '@osd/utils';

import { MyServiceProvider } from './services/my_service';
import { MyAppPageProvider } from './services/my_app_page';

// the default export of config files must be a config provider
// that returns an object with the projects config values
export default async function ({ readConfigFile }) {

  // read the {osd} config file so that we can utilize some of
  // its services and PageObjects
  const opensearchDashboardsConfig = await readConfigFile(resolve(REPO_ROOT, 'test/functional/config.js'));

  return {
    // list paths to the files that contain your plugins tests
    testFiles: [
      resolve(__dirname, './my_test_file.js'),
    ],

    // define the name and providers for services that should be
    // available to your tests. If you don't specify anything here
    // only the built-in services will be available
    services: {
      ...opensearchDashboardsConfig.get('services'),
      myService: MyServiceProvider,
    },

    // just like services, PageObjects are defined as a map of
    // names to Providers. Merge in {osd}'s or pick specific ones
    pageObjects: {
      management: opensearchDashboardsConfig.get('pageObjects.management'),
      myApp: MyAppPageProvider,
    },

    // the apps section defines the urls that
    // `PageObjects.common.navigateTo(appKey)` will use.
    // Merge urls for your plugin with the urls defined in
    // {osd}'s config in order to use this helper
    apps: {
      ...opensearchDashboardsConfig.get('apps'),
      myApp: {
        pathname: '/app/my_app',
      }
    },

    // choose where opensearchArchiver should load archives from
    opensearchArchiver: {
      directory: resolve(__dirname, './opensearcharchives'),
    },

    // choose where screenshots should be saved
    screenshots: {
      directory: resolve(__dirname, './tmp/screenshots'),
    }

    // more settings, like timeouts, mochaOpts, etc are
    // defined in the config schema. See {blob}src/functional_test_runner/lib/config/schema.js[src/functional_test_runner/lib/config/schema.js]
  };
}

-----------

From the root of your repo you should now be able to run the `FunctionalTestRunner` script from your plugin project.

["source","shell"]
-----------
node ../../opensearch-dashboards/scripts/functional_test_runner
-----------

[discrete]
=== Using opensearchArchiver

We're working on documentation for this, but for now the best place to look is the original {osd-repo}/issues/10359[pull request].

