[[role-management-api-put]]
=== Create or update role API
++++
<titleabbrev>Create or update role</titleabbrev>
++++

experimental[] Create a new {osd} role, or update the attributes of an existing role. {osd} roles are stored in the
{opensearch} native realm.

[[role-management-api-put-request]]
==== Request

`PUT <opensearchDashboards host>:<port>/api/security/role/my_opensearch_dashboards_role`

[[role-management-api-put-prereqs]]
==== Prerequisite

To use the create or update role API, you must have the `manage_security` cluster privilege.

[role="child_attributes"]
[[role-management-api-response-body]]
==== Request body

`metadata`::
  (Optional, object) In the `metadata` object, keys that begin with `_` are reserved for system usage.

`opensearch`::
  (Optional, object) {opensearch} cluster and index privileges. Valid keys include
  `cluster`, `indices`, and `run_as`. For more information, see
  {ref}/defining-roles.html[Defining roles].

`opensearchDashboards`::
  (list) Objects that specify the <<opensearch-dashboards-privileges, OpenSearchDashboards privileges>> for the role.
+
.Properties of `opensearchDashboards`
[%collapsible%open]
=====
`base` :::
  (Optional, list) A base privilege. When specified, the base must be `["all"]` or `["read"]`.
  When the `base` privilege is specified, you are unable to use the `feature` section.
  "all" grants read/write access to all {osd} features for the specified spaces.
  "read" grants read-only access to all {osd} features for the specified spaces.

`feature` :::
  (object) Contains privileges for specific features.
  When the `feature` privileges are specified, you are unable to use the `base` section.
  To retrieve a list of available features, use the <<features-api-get, features API>>.

`spaces` :::
  (list) The spaces to apply the privileges to.
  To grant access to all spaces, set to `["*"]`, or omit the value.
=====

[[role-management-api-put-response-codes]]
==== Response code

`204`::
  Indicates a successful call.

==== Examples

Grant access to various features in all spaces:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/security/role/my_opensearch_dashboards_role
{
  "metadata" : {
    "version" : 1
  },
  "opensearch": {
    "cluster" : [ ],
    "indices" : [ ]
  },
  "opensearchDashboards": [
    {
      "base": [],
      "feature": {
       "discover": [
          "all"
        ],
        "visualize": [
          "all"
        ],
        "dashboard": [
          "all"
        ],
        "dev_tools": [
          "read"
        ],
        "advancedSettings": [
          "read"
        ],
        "indexPatterns": [
          "read"
        ],
        "timelion": [
          "all"
        ],
        "graph": [
          "all"
        ],
        "apm": [
          "read"
        ],
        "maps": [
          "read"
        ],
        "canvas": [
          "read"
        ],
        "infrastructure": [
          "all"
        ],
        "logs": [
          "all"
        ],
        "uptime": [
          "all"
        ]
      },
      "spaces": [
        "*"
      ]
    }
  ]
}
--------------------------------------------------
// OPENSEARCH_DASHBOARDS

Grant dashboard-only access to only the Marketing space:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/security/role/my_opensearch_dashboards_role
{
  "metadata" : {
    "version" : 1
  },
  "opensearch": {
    "cluster" : [ ],
    "indices" : [ ]
  },
  "opensearchDashboards": [
    {
      "base": [],
      "feature": {
        "dashboard": ["read"]
      },
      "spaces": [
        "marketing"
      ]
    }
  ]
}
--------------------------------------------------
// OPENSEARCH_DASHBOARDS

Grant full access to all features in the Default space:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/security/role/my_opensearch_dashboards_role
{
  "metadata" : {
    "version" : 1
  },
  "opensearch": {
    "cluster" : [ ],
    "indices" : [ ]
  },
  "opensearchDashboards": [
    {
      "base": ["all"],
      "feature": {
      },
      "spaces": [
        "default"
      ]
    }
  ]
}
--------------------------------------------------
// OPENSEARCH_DASHBOARDS

Grant different access to different spaces:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/security/role/my_opensearch_dashboards_role
{
  "metadata" : {
    "version" : 1
  },
  "opensearch": {
    "cluster" : [ ],
    "indices" : [ ]
  },
  "opensearchDashboards": [
    {
      "base": [],
      "feature": {
        "discover": ["all"],
        "dashboard": ["all"]
      },
      "spaces": [
        "default"
      ]
    },
    {
      "base": ["read"],
      "spaces": [
        "marketing",
        "sales"
      ]
    }
  ]
}
--------------------------------------------------
// OPENSEARCH_DASHBOARDS

Grant access to {osd} and {opensearch}:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/security/role/my_opensearch_dashboards_role
{
  "metadata" : {
    "version" : 1
  },
  "opensearch": {
    "cluster" : [ "all" ],
    "indices" : [ {
      "names" : [ "index1", "index2" ],
      "privileges" : [ "all" ],
      "field_security" : {
        "grant" : [ "title", "body" ]
      },
      "query" : "{\"match\": {\"title\": \"foo\"}}"
    } ]
  },
  "opensearchDashboards": [
    {
      "base": ["all"],
      "feature": {
      },
      "spaces": [
        "default"
      ]
    }
  ]
}
--------------------------------------------------
// OPENSEARCH_DASHBOARDS
