[[saved-objects-api]]
== Saved objects APIs

Manage {osd} saved objects, including dashboards, visualizations, index patterns, and more.

WARNING: Do not write documents directly to the `.opensearch-dashboards` index. When you write directly
to the `.opensearch-dashboards` index, the data becomes corrupted and permanently breaks future {osd} versions.

The following saved objects APIs are available: 

* <<saved-objects-api-get, Get object API>> to retrieve a single {osd} saved object by ID

* <<saved-objects-api-bulk-get, Bulk get objects API>> to retrieve multiple {osd} saved objects by ID

* <<saved-objects-api-find, Find objects API>> to retrieve a paginated set of {osd} saved objects by various conditions

* <<saved-objects-api-create, Create saved object API>> to create {osd} saved objects

* <<saved-objects-api-bulk-create, Bulk create saved objects API>> to create multiple {osd} saved objects

* <<saved-objects-api-update, Update object API>> to update the attributes for existing {osd} saved objects

* <<saved-objects-api-delete, Delete object API>> to remove {osd} saved objects

* <<saved-objects-api-export, Export objects API>> to retrieve sets of saved objects that you want to import into {osd}

* <<saved-objects-api-import, Import objects API>> to create sets of {osd} saved objects from a file created by the export API

* <<saved-objects-api-resolve-import-errors, Resolve import errors API>> to resolve errors from the import API

* <<saved-objects-api-rotate-encryption-key, Rotate encryption key API>> to rotate the encryption key for encrypted saved objects

include::saved-objects/get.asciidoc[]
include::saved-objects/bulk_get.asciidoc[]
include::saved-objects/find.asciidoc[]
include::saved-objects/create.asciidoc[]
include::saved-objects/bulk_create.asciidoc[]
include::saved-objects/update.asciidoc[]
include::saved-objects/delete.asciidoc[]
include::saved-objects/export.asciidoc[]
include::saved-objects/import.asciidoc[]
include::saved-objects/resolve_import_errors.asciidoc[]
include::saved-objects/rotate_encryption_key.asciidoc[]
