[[add-data-tutorials]]
== Add data tutorials

`Add Data` in the {osd} Home application contains tutorials for setting up data flows in the Elastic stack.

Each tutorial contains three sets of instructions:

* `On Premise.` Set up a data flow when both {osd} and {opensearch} are running on premise.
* `On Premise Elastic Cloud.` Set up a data flow when {osd} is running on premise and {opensearch} is running on Elastic Cloud.
* `Elastic Cloud.` Set up a data flow when both {osd} and {opensearch} are running on Elastic Cloud.

[discrete]
=== Creating a new tutorial
1. Create a new directory in the link:https://github.com/elastic/opensearch-dashboards/tree/master/src/plugins/home/server/tutorials[tutorials directory].
2. In the new directory, create a file called `index.ts` that exports a function.
The function must return a function object that conforms to the `TutorialSchema` interface link:{osd-repo}tree/{branch}/src/plugins/home/server/services/tutorials/lib/tutorial_schema.ts[tutorial schema].
3. Register the tutorial in link:{osd-repo}tree/{branch}/src/plugins/home/server/tutorials/register.ts[register.ts] by adding it to the `builtInTutorials`.
// TODO update path once assets are migrated
4. Add image assets to the link:{osd-repo}tree/{branch}/src/legacy/core_plugins/opensearch-dashboards/public/home/tutorial_resources[tutorial_resources directory].
5. Run {osd} locally to preview the tutorial.
6. Create a PR and go through the review process to get the changes approved.

If you are creating a new plugin and the tutorial is only related to that plugin, you can also place the `TutorialSchema` object into your plugin folder. Add `home` to the `requiredPlugins` list in your `opensearch_dashboards.json` file.
Then register the tutorial object by calling `home.tutorials.registerTutorial(tutorialObject)` in the `setup` lifecycle of your server plugin.

[discrete]
==== Variables
String values can contain variables that are substituted when rendered. Variables are specified by `{}`.
For example: `{config.docs.version}` is rendered as `6.2` when running the tutorial in {osd} 6.2.

link:{osd-repo}tree/{branch}/src/plugins/home/public/application/components/tutorial/replace_template_strings.js[Provided variables]

[discrete]
==== Markdown
String values can contain limited Markdown syntax.

link:{osd-repo}tree/{branch}/src/legacy/core_plugins/opensearch-dashboards/public/home/components/tutorial/content.js[Enabled Markdown grammars]

