[role="xpack"]
[[xpack-security-audit-logging]]
=== Audit logs

You can enable auditing to keep track of security-related events such as
authorization success and failures. Logging these events enables you
to monitor {osd} for suspicious activity and provides evidence in the
event of an attack.

Use the {osd} audit logs in conjunction with {opensearch}'s
audit logging to get a holistic view of all security related events. 
{osd} defers to {opensearch}'s security model for authentication, data
index authorization, and features that are driven by cluster-wide privileges.
For more information on enabling audit logging in {opensearch}, see
{ref}/auditing.html[Auditing security events].

[IMPORTANT]
============================================================================
Audit logs are **disabled** by default. To enable this functionality, you
must set `xpack.security.audit.enabled` to `true` in `opensearch_dashboards.yml`.
============================================================================

Audit logging uses the standard {osd} logging output, which can be configured
in the `opensearch_dashboards.yml` and is discussed in <<settings>>.

==== Audit event types

When you are auditing security events, each request can generate 
multiple audit events. The following is a list of the events that can be generated:

|======
| `saved_objects_authorization_success`    | Logged when a user is authorized to access a saved
                                             objects when using a role with <<opensearch-dashboards-privileges>>
| `saved_objects_authorization_failure`    | Logged when a user isn't authorized to access a saved
                                             objects when using a role with <<opensearch-dashboards-privileges>>
|======
