/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  ApiGatewayIcon,
  ApplicationIcon,
  AppMeshIcon,
  AppRunnerIcon,
  AppSyncIcon,
  AutoScalingIcon,
  BedrockIcon,
  CloudFormationIcon,
  CloudFrontIcon,
  CloudTrailIcon,
  CloudWatchIcon,
  DynamodbIcon,
  EbsIcon,
  Ec2Icon,
  EcsIcon,
  EksIcon,
  ElasticacheIcon,
  ElasticBeanstalkIcon,
  ElasticLoadbalancingIcon,
  EmrIcon,
  EventBridgeIcon,
  FargateIcon,
  GlacierIcon,
  K8sIcon,
  KinesisIcon,
  LambdaIcon,
  LoadBalancerIcon,
  MacieIcon,
  PrometheusIcon,
  RdsIcon,
  RedShiftIcon,
  Route53Icon,
  RumIcon,
  S3Icon,
  ServiceIcon,
  ServiceLensUnknownNodeIcon,
  SnsIcon,
  SqsIcon,
  StepFunctionIcon,
  SyntheticsIcon,
  VpcIcon,
} from '../resources/services';
// import { type ComponentProps, FC } from 'react';

export const ICONS: { [key: string]: any } = {
  'AWS::APIGateway': ApiGatewayIcon,
  'AWS::APM::Service': ServiceLensUnknownNodeIcon,
  'AWS::ApplicationSignals::Application': ApplicationIcon,
  'AWS::AppMesh': AppMeshIcon,
  'AWS::AppMesh::Mesh': AppMeshIcon,
  'AWS::AppRunner': AppRunnerIcon,
  'AWS::AppRunner::Service': AppRunnerIcon,
  'AWS::AppSync': AppSyncIcon,
  'AWS::AppSync::GraphQLApi': AppSyncIcon,
  'AWS::AutoScaling': AutoScalingIcon,
  'AWS::AutoScaling::AutoScalingGroup': AutoScalingIcon,
  'AWS::Bedrock': BedrockIcon,
  'AWS::Bedrock::Model': BedrockIcon,
  'AWS::CloudFormation': CloudFormationIcon,
  'AWS::CloudFormation::Stack': CloudFormationIcon,
  'AWS::CloudFront': CloudFrontIcon,
  'AWS::CloudFront::Distribution': CloudFrontIcon,
  'AWS::CloudTrail': CloudTrailIcon,
  'AWS::CloudTrail::Trail': CloudTrailIcon,
  'AWS::CloudWatch': CloudWatchIcon,
  'AWS::CloudWatch::Alarm': CloudWatchIcon,
  'AWS::CloudWatch::Service': CloudWatchIcon,
  'AWS::DynamoDB': DynamodbIcon,
  'AWS::DynamoDB::Table': DynamodbIcon,
  'AWS::EC2::Volume': EbsIcon,
  'AWS::EC2': Ec2Icon,
  'AWS::EC2::Instance': Ec2Icon,
  'AWS::ECS': EcsIcon,
  'AWS::ECS::Service': FargateIcon,
  'AWS::ECS::Cluster': EcsIcon,
  'AWS::EKS': EksIcon,
  'AWS::EKS::Cluster': EksIcon,
  'AWS::Endpoint': ServiceLensUnknownNodeIcon,
  'AWS::ElastiCache': ElasticacheIcon,
  'AWS::ElastiCache::CacheCluster': ElasticacheIcon,
  'AWS::ElasticBeanstalk': ElasticBeanstalkIcon,
  'AWS::ElasticBeanstalk::Application': ElasticBeanstalkIcon,
  'AWS::ElasticLoadBalancing': ElasticLoadbalancingIcon,
  'AWS::ElasticLoadBalancing::LoadBalancer': ElasticLoadbalancingIcon,
  'AWS::ElasticLoadBalancingV2::LoadBalancer': ElasticLoadbalancingIcon,
  'AWS::EMR': EmrIcon,
  'AWS::EMR::Cluster': EmrIcon,
  'AWS::Events': EventBridgeIcon,
  'AWS::Events::Rule': EventBridgeIcon,
  'AWS::Glacier': GlacierIcon,
  'AWS::Glacier::Vault': GlacierIcon,
  'AWS::Kinesis': KinesisIcon,
  'AWS::Kinesis::Stream': KinesisIcon,
  K8s: K8sIcon,
  'AWS::Kubernetes': K8sIcon,
  'AWS::Macie': MacieIcon,
  'AWS::Macie::CustomDataIdentifier': MacieIcon,
  'AWS::APS': PrometheusIcon,
  'AWS::APS::Workspace': PrometheusIcon,
  'AWS::RDS': RdsIcon,
  'AWS::RDS::DBInstance': RdsIcon,
  'AWS::Redshift': RedShiftIcon,
  'AWS::Redshift::Cluster': RedShiftIcon,
  'AWS::Route53': Route53Icon,
  'AWS::Route53::HostedZone': Route53Icon,
  'AWS::Route53::RecordSet': Route53Icon,
  'AWS::Lambda': LambdaIcon,
  'AWS::LoadBalancer': LoadBalancerIcon,
  'AWS::Resource': ServiceIcon,
  'AWS::RUM::AppMonitor': RumIcon,
  'AWS::RUM::Monitor': RumIcon,
  'AWS::S3': S3Icon,
  'AWS::S3::Bucket': S3Icon,
  'AWS::SNS': SnsIcon,
  'AWS::SNS::Topic': SnsIcon,
  'AWS::SQS': SqsIcon,
  'AWS::SQS::Queue': SqsIcon,
  'AWS::Synthetics': SyntheticsIcon,
  'AWS::Synthetics::Canary': SyntheticsIcon,
  'AWS::StepFunctions': StepFunctionIcon,
  'AWS::StepFunctions::StateMachine': StepFunctionIcon,
  'AWS::EC2::VPC': VpcIcon,
  'AWS::TargetGroup': LoadBalancerIcon,
  'Remote::Endpoint': ServiceLensUnknownNodeIcon,
  Generic: ServiceLensUnknownNodeIcon,
  Unknown: ServiceLensUnknownNodeIcon,
};
