[[telemetry-settings-osd]]
=== Telemetry settings in {osd}
++++
<titleabbrev>Telemetry settings</titleabbrev>
++++

By default, Usage Collection (also known as Telemetry) is enabled. This
helps us learn about the {osd} features that our users are most interested in, so we
can focus our efforts on making them even better.

You can control whether this data is sent from the {osd} servers, or if it should be sent
from the user's browser, in case a firewall is blocking the connections from the server. Additionally, you can decide to completely disable this feature either in the config file or in {osd} via *Management > OpenSearchDashboards > Advanced Settings > Usage Data*.

See our https://www.elastic.co/legal/privacy-statement[Privacy Statement] to learn more.

[float]
[[telemetry-general-settings]]
==== General telemetry settings

[cols="2*<"]
|===
|[[telemetry-enabled]] `telemetry.enabled`
  | Set to `true` to send cluster statistics to Elastic. Reporting your
  cluster statistics helps us improve your user experience. Your data is never
  shared with anyone. Set to `false` to disable statistics reporting from any
  browser connected to the {osd} instance. Defaults to `true`.

| `telemetry.sendUsageFrom`
  | Set to `'server'` to report the cluster statistics from the {osd} server.
  If the server fails to connect to our endpoint at https://telemetry.elastic.co/, it assumes
  it is behind a firewall and falls back to `'browser'` to send it from users' browsers
  when they are navigating through {osd}. Defaults to `'server'`.

|[[telemetry-optIn]] `telemetry.optIn`
  | Set to `true` to automatically opt into reporting cluster statistics. You can also opt out through
  *Advanced Settings* in {osd}. Defaults to `true`.

| `telemetry.allowChangingOptInStatus`
  | Set to `true` to allow overwriting the <<telemetry-optIn, `telemetry.optIn`>> setting via the {osd} UI. Defaults to `true`. +

|===

[NOTE]
============
When `false`, <<telemetry-optIn, `telemetry.optIn`>> must be `true`. To disable telemetry and not allow users to change that parameter, use <<telemetry-enabled, `telemetry.enabled`>>.
============
