name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # opensearch-trigger-bot installation ID
          installation_id: 22958780

      # Using fork of https://github.com/tibdex/backport
      # https://github.com/tibdex/backport/pull/81
      - name: Backport
        uses: VachaShah/backport@v1.1.4
        with:
          github_token: ${{ steps.github_app_token.outputs.token }}
          branch_name: backport/backport-${{ github.event.number }}
