name: Bundler Performance Testing

on:
  workflow_call:

jobs:
  bundle-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Yarn
        run: |
          npm uninstall -g yarn
          npm i -g yarn@1.22.10

      - name: Run bootstrap
        # Install dependencies and bootstrap the OpenSearch Dashboards project
        run: yarn osd bootstrap

      - name: Build plugins
        # Build OpenSearch Dashboards platform plugins without examples using 12 workers
        run: node scripts/build_opensearch_dashboards_platform_plugins --no-examples --workers 12

      - name: Update Limit and bundle size variation
        # This command updates the limit and bundle size variation for the OpenSearch Dashboards platform plugins
        run: node scripts/build_opensearch_dashboards_platform_plugins --update-limits

      - name: Save Bundle Analysis Results
        if: ${{ hashFiles('packages/osd-optimizer/limits_delta.yml') != '' }}
        run: |
          echo "📊 **Bundle Size crossed 5% for below plugins**" > bundle_analysis.txt
          echo "" >> bundle_analysis.txt
          cat packages/osd-optimizer/limits_delta.yml >> bundle_analysis.txt

      - name: Check if bundle_analysis.txt exists
        id: check_file
        run: |
          if [ -f bundle_analysis.txt ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Analysis Artifact
        if: ${{ hashFiles('packages/osd-optimizer/limits_delta.yml') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-results
          path: bundle_analysis.txt
