name: Bundler Performance Testing

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md' # Ignore documentation files
      - '**/*.test.ts' # Ignore test files (TypeScript)
      - '**/*.test.js' # Ignore test files (JavaScript)
      - '**/__tests__/**' # Ignore test directories
      - '.github/workflows/**' # Ignore GitHub workflow files
      - 'docs/**' # Ignore entire docs directory
permissions:
  contents: read
  pull-requests: write
  statuses: write
  issues: write

jobs:
  bundle-analyzer:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Yarn
        run: |
          npm uninstall -g yarn
          npm i -g yarn@1.22.10

      - name: Run bootstrap
        # Install dependencies and bootstrap the OpenSearch Dashboards project
        run: yarn osd bootstrap

      - name: Build plugins
        # Build OpenSearch Dashboards platform plugins without examples using 12 workers
        run: node scripts/build_opensearch_dashboards_platform_plugins --no-examples --workers 12

      - name: Update Limit and bundle size variation
        # This command updates the limit and bundle size variation for the OpenSearch Dashboards platform plugins
        run: node scripts/build_opensearch_dashboards_platform_plugins --update-limits

      - name: Save Bundle Analysis Results
        if: ${{ hashFiles('packages/osd-optimizer/limits_delta.yml') != '' }}
        run: |
          echo "📊 **Bundle Size crossed 5% for below plugins**" > bundle_analysis.txt
          echo "" >> bundle_analysis.txt
          cat packages/osd-optimizer/limits_delta.yml >> bundle_analysis.txt

      - name: Upload Analysis Artifact
        if: ${{ hashFiles('packages/osd-optimizer/limits_delta.yml') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-results
          path: bundle_analysis.txt
